[package]
name = "aardvark"
version = "0.1.0"
edition = "2021"

[dependencies]
aardvark-node = { path = "../aardvark-node" }
anyhow = "1.0.94"
automerge = "0.5.12"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.9", package = "gtk4", features = ["gnome_47"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.42.0", features = ["full"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
sourceview = { package = "sourceview5", version = "0.9" }

[dependencies.adw]
package = "libadwaita"
version = "0.7"
features = ["v1_6"]
