[package]
name = "aardvark-doc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
async-channel = "2.3.1"
loro = "1.2.7"

[dev-dependencies]
tokio = { version = "1.43.0", features = ["macros", "test-util"] }
