[package]
name = "aardvark-doc"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
loro = "1.3.1"
thiserror = "2.0.11"

[dev-dependencies]
tokio = { version = "1.42.0", features = ["macros", "test-util"] }
